trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'sc-azure-sdet-learning'
    KeyVaultName: 'kv-sdet-learning-01'
    SecretsFilter: '*'
    RunAsPreJob: false

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    echo EMAIL=$(automation-email)
    echo PASSWORD_EXISTS=$(automation-password)
  displayName: 'Verify Key Vault Variables'

- script: |
    pytest
  displayName: 'Run Pytest Tests'
  env:
    automation-email: $(automation-email)
    automation-password: $(automation-password)
    blob-connection-string: $(blob-connection-string)
    
- script: |
    python upload_runner.py
  displayName: 'Upload Report To Blob Storage'