trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'

- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'sc-azure-sdet-learning'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
      az keyvault secret list --vault-name kv-sdet-learning-01

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    pytest
  displayName: 'Run Pytest Tests'